version: '3'

services:
  gpt4free:
    image: hlohaus789/g4f:latest
    shm_size: 2gb
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
    ports:
      - '8089:1337'  # external:internal (maps your host 8081 → container 1337)
      - '7900:7900'
    environment:
      - OLLAMA_HOST=host.docker.internal
